---
title: "Practical Machine Learning Project Writeup"
author: "Paul Nakonechny"
date: "June 17, 2015"
output: html_document
---

#Introduction


```{r}
#Set working directory
setwd("~/Desktop/Practical Machine Learning")

#Load packages
library(caret)

#Download files
download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", 
              "pml-training.csv", method = "curl")
download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", 
              "pml-testing.csv", method = "curl")

#Read data
training <- read.csv("pml-training.csv")
testing<- read.csv("pml-testing.csv")
```

#Data Cleaning

```{r}
#Remove Columns that have more than 60% NA values, remove timestamps and ID
training <- training[,colSums(is.na(testing))/nrow(testing) <= .6]
training <- training[,6:60]
```

#Data Partition
```{r}
#Create a validation set from the training set
set.seed(2)
inTrain <- createDataPartition(y = training$classe, p = .75, list = FALSE)

training <- training[inTrain,]
validation <- training[-inTrain,]
```

#Model Creation
Cross validation and error rates
```{r}
set.seed(2)
modFitRF <- train(classe ~ ., method = "rf", prox = TRUE, data = training, 
                  trControl = trainControl(method = "cv", number = 5), allowParallel = TRUE)
modFitRF

#Estimate of error rate: 0.22%
modFitRF$finalModel
```

#Test against validation set

```{r}
#Fit model against validation set
predvalRF <- predict(modFitRF, newdata = validation)
confusionMatrix(predvalRF, validation$classe)
```

#Fit model against testing set

```{r}
#Fit model against testing set
predTestRF <- predict(modFitRF, newdata = testing)
predTestRF
```

#Conclusion
